try 6.1-20260603.072225-arm64

diff --git a/.github/workflows/lvm-load.yaml b/.github/workflows/lvm-load.yaml
--- a/.github/workflows/lvm-load.yaml
+++ b/.github/workflows/lvm-load.yaml
@@ -16,10 +16,9 @@ jobs:
       matrix:
         kernel:
           # https://quay.io/repository/lvh-images/kind?tab=tags
-          - "6.6-main-amd64"
           - "6.6-20260603.072225-amd64"
-          - "5.15-main-amd64"
-          - "5.15-20260603.072225-amd64"
+          - "6.1-20260603.072225-arm64"
+          # - "5.15-20260603.072225-amd64" # not supported
     timeout-minutes: 15
     steps:
       - uses: actions/checkout@v4
@@ -51,86 +50,45 @@ jobs:
               2>&1 | tee /tmp/bpf-load.log
 
             sudo bpftool prog show
-  load-vm-arm64:
-    runs-on: ubuntu-24.04-arm
-    name: eBPF ARM Load Test
-    strategy:
-      fail-fast: false
-      matrix:
-        kernel:
-          - "6.6-main-arm64"
-          - "5.15-main-arm64"
-    steps:
-      - uses: actions/checkout@v4
-      - name: Load NetLedger Agent in ${{ matrix.kernel }}
-        uses: cilium/little-vm-helper@v0.0.30
-        with:
-          test-name: load-netledger
-          image: "kind"
-          arch: "arm64"
-          image-version: ${{ matrix.kernel }}
-          host-mount: ${{ github.workspace }}
-          install-dependencies: "true"
-          ssh-connect-wait-timeout: "2"
-          cmd: |
-            set -euo pipefail
+  # ARM64 does not work with ubuntu-24.04-arm runner
+  # load-vm-arm64:
+  #   runs-on: ubuntu-24.04-arm
+  #   name: eBPF ARM Load Test
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       kernel:
+  #         - "6.6-20260603.072225-amd64"
+  #         - "5.15-20260603.072225-amd64"
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - name: Load NetLedger Agent in ${{ matrix.kernel }}
+  #       uses: cilium/little-vm-helper@v0.0.30
+  #       with:
+  #         test-name: load-netledger
+  #         image: "kind"
+  #         arch: "arm64"
+  #         image-version: ${{ matrix.kernel }}
+  #         host-mount: ${{ github.workspace }}
+  #         install-dependencies: "true"
+  #         ssh-connect-wait-timeout: "2"
+  #         cmd: |
+  #           set -euo pipefail
 
-            # print kernel version
-            echo "Kernel Version: "
-            uname -a
+  #           # print kernel version
+  #           echo "Kernel Version: "
+  #           uname -a
 
-            # goto where host is mounted
-            echo ""
-            cd /host
-            ls -lah
+  #           # goto where host is mounted
+  #           echo ""
+  #           cd /host
+  #           ls -lah
 
-            echo ""
-            sudo bpftool prog loadall \
-              ./internal/agent/bpf/netledger_bpfel.o \
-              /sys/fs/bpf/netledger \
-              2>&1 | tee /tmp/bpf-load.log
+  #           echo ""
+  #           sudo bpftool prog loadall \
+  #             ./internal/agent/bpf/netledger_bpfel.o \
+  #             /sys/fs/bpf/netledger \
+  #             2>&1 | tee /tmp/bpf-load.log
 
-            sudo bpftool prog show
-    # steps:
-    #   - uses: actions/checkout@v4
-
-    #   - name: Install tools
-    #     run: |
-    #       sudo apt-get update
-
-    #       sudo apt-get install -y \
-    #         clang \
-    #         llvm \
-    #         linux-tools-common || true
-
-    #       sudo apt-get install -y linux-tools-$(uname -r) \
-    #          linux-cloud-tools-$(uname -r) \
-    #          linux-tools-azure \
-    #          linux-cloud-tools-azure || true
-    #   - name: Check bpftool
-    #     run: |
-    #       echo "Ensure bpftool exists somewhere"
-    #       which bpftool || true
-    #   - name: Setup BPF filesystem
-    #     run: |
-    #       sudo mount -t bpf bpf /sys/fs/bpf || true
-    #   - name: Load BPF program (host kernel only)
-    #     run: |
-    #       set -euxo pipefail
-
-    #       uname -a
-
-    #       bpftool prog loadall \
-    #         ./internal/agent/bpf/netledger_bpfel.o \
-    #         /sys/fs/bpf/netledger \
-    #         2>&1 | tee /tmp/bpf-load.log
-
-    #   - name: Show loaded programs
-    #     if: always()
-    #     run: |
-    #       sudo bpftool prog show
-
-    #   - name: Show verifier log on failure
-    #     if: failure()
-    #     run: |
-    #       cat /tmp/bpf-load.log || true
+  #           sudo bpftool prog show
+    
